Controllers/RootController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AspNetCoreVueTypescriptStarter.Infrastructure.Filters;

namespace AspNetCoreVueTypescriptStarter.Controllers
{
    /// <summary>
    /// The root controller is just used to define new page routes. This be one of the few MVC controllers
    /// you will need. 
    /// </summary>
    [LoggingFilter]
    public class RootController : BaseController
    {
        public RootController(ILoggerFactory loggerFactory,
                              ApplicationConfig applicationConfig,
                              IHttpContextAccessor ctxAccessor) : base(loggerFactory, applicationConfig, ctxAccessor)
        {
        }

        /// <summary>
        /// Home is Here
        /// </summary>
        /// <returns></returns>
        [Route("/")]
        //[Route("Dashboard")]
        public IActionResult Index()
        {
            return View();
        }

        // Example new page / route. For new pages create a matching View.cshtml page in the view folder.
        //[Route("Search")]
        //public IActionResult Search()           => View();

    }
}

Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Page Not Found";
}

<component inline-template is="notFoundPage">
    <v-layout row wrap class="full-height">
        <v-flex xs12 lg10>
            <v-card hover class="ma-2">
                <v-card-title>
                    <h1 class="headline">Oops! This page doesn't exist</h1>
                </v-card-title>
                <v-card-text class="flex-spacer">
                    <iframe src="https://www.youtube.com/embed/SIaFtAKnqBU?vq=hd720&rel=0&showinfo=0&controls=0&iv_load_policy=3&loop=1&playlist=SIaFtAKnqBU&modestbranding=1&autoplay=1"
                            height="500" width="100%" frameborder="0" webkitAllowFullScreen allowFullScreen></iframe>
                    <p class="headline">
                        Not to worry. You can either head back to home, or sit here and listen to a goat scream like
                        a human.
                    </p>
                    <p>
                        Please head back and try again.
                    </p>
                </v-card-text>
                <v-card-actions>
                    <p>
                        <v-btn color="primary" v-on:click="imFrustrated">click here</v-btn> to check your frustation level ...
                    </p>
                    <v-progress-circular v-show="frustrationLevel > 0" size="75"
                                         width="15"
                                         rotate="360"
                                         v-bind:value="frustrationLevel"
                                         v-bind:color="levelColor">
                        {{frustrationLevel}}
                    </v-progress-circular>
                </v-card-actions>
            </v-card>
        </v-flex>
    </v-layout>
</component>

@section Scripts {
}

Views/Shared/UnAuthorized.cshtml
@{
  ViewData["Title"] = "UnAuthorized";
}

<component inline-template is="unauthorizedPage">
    <v-layout row wrap class="full-height">
        <v-card hover class="ma-2">
            <v-card-title>
                <h1 class="display-1">Unauthorized!</h1>
            </v-card-title>
            <v-card-text class="flex-spacer">
                <p class="headline">
                    Oops! It appears you are unauthorized to access this page.
                </p>
                <p class="body-2">
                    If you need or should have access to this resource then please contact the Helpdesk.
                </p>
                <ul>
                    <li>Phone</li>
                    <li>Email</li>
                    <li>Fax</li>
                    <li>Address</li>
                </ul>
            </v-card-text>
            <v-card-actions>
            </v-card-actions>
        </v-card>
    </v-layout>
</component>

@section Scripts {
}

Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Authorization
@using AspNetCoreVueTypescriptStarter.Infrastructure.Extensions
@using AspNetCoreVueTypescriptStarter.Models
@inject IAuthorizationService AuthorizationService
@{
    var assemblyversion = ViewBag.Version as Version ?? new Version(0, 0, 0, 0); //major,minor/
    var ver = (assemblyversion.Major < 1) ? $"(BETA: {assemblyversion.Major}:{assemblyversion.Minor}:{assemblyversion.Build}:{assemblyversion.MinorRevision} )" : "";
    var appname = "Starter";
}
<header>
    <v-navigation-drawer persistent
                         enable-resize-watcher
                         v-model="navDrawer"
                         app>
        @* shows list of authorized apps - authorize in pucidentity db *@
        <v-layout row style="padding-top: 65px;">
            <v-flex xs2>
            </v-flex>
            <v-flex>
                <v-toolbar card prominent style="background-color: white;">
                    <v-toolbar-title class="title">@appname</v-toolbar-title>
                </v-toolbar>
            </v-flex>
        </v-layout>
        <v-divider></v-divider>
        <v-list class="pt-2">
            @* add new pages to side nav here *@
            <v-list-tile class="mt-0" href="@Url.Action("Index", "Root")">
                <v-list-tile-content>
                    <v-list-tile-title class="subheading"><v-icon class="pl-2 pr-3">dashboard</v-icon>Home</v-list-tile-title>
                </v-list-tile-content>
            </v-list-tile>
        </v-list>
    </v-navigation-drawer>
    <v-toolbar fixed app clipped-left dark color="blue darken-3" flat>
        <v-toolbar-side-icon v-on:click.stop="navDrawer = !navDrawer" aria-label="Side Navigation Drawer"></v-toolbar-side-icon>
        <v-toolbar-title style="width: 350px" class="ml-0 pl-3">
            <v-icon dark>flash_on</v-icon>
            <span class="hidden-sm-and-down">Public Utility Commission</span>
            <span class="hidden-md-and-up">PUCT</span>
        </v-toolbar-title>
        <v-spacer></v-spacer>
        
        @* User Info Dropdown menu *@
        <v-menu bottom :close-on-content-click="true"
                class="hidden-sm-and-down"
                allow-overflow
                max-height="600" style="z-index: 301;">
            <v-btn icon slot="activator" aria-label="User Info">
                <v-avatar size="38">
                    <img src="@ViewBag.UserInfo?.Photo" alt="Avatar">
                </v-avatar>
            </v-btn>
            <v-card>
                <div style="overflow: auto; max-height: 600px;">
                    <v-list>
                        <v-list-tile style="height: 14px;"><v-list-tile-title style="font-size: small;">Username: @ViewBag.UserInfo?.UserName</v-list-tile-title></v-list-tile>
                        <v-list-tile style="height: 14px;"><v-list-tile-title style="font-size: small;">Email: @ViewBag.UserInfo?.Email</v-list-tile-title></v-list-tile>
                        <v-list-tile style="height: 14px;"><v-list-tile-title style="font-size: small;">Phone: @ViewBag.UserInfo?.Phone</v-list-tile-title></v-list-tile>
                        <v-list-tile style="height: 10px;"><v-list-tile-title style="font-size: small;">App Version: @ver</v-list-tile-title></v-list-tile>
                        <v-divider class="mt-4"></v-divider>
                     </v-list>
                </div>
            </v-card>
        </v-menu>
        <span class="text-xs-right hidden-xs-only" style="font-size: medium;">@ViewBag.UserInfo?.Name</span>
    </v-toolbar>
</header>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]-@ViewData["AppName"]</title>

    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
    <environment include="Development">
        <link rel="stylesheet" href="~/dist/vendor.css" />
        <link rel="stylesheet" href="~/css/puc.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment include="Production">
        <link rel="stylesheet" href="~/dist/vendor.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/puc.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div id="app-root" v-cloak ref="app">
        <v-app light>
            @await Html.PartialAsync("_HeaderPartial")
            <v-content style="background-color: whitesmoke;">
                <v-container fluid class="pt-0 mt-0 pr-0 pl-0">
                    @* <v-slide-y-transition mode="out-in"> *@
                        <v-layout column align-top ref="page">
                            @Html.AntiForgeryToken()
                            @RenderBody()
                        </v-layout>
                    @* </v-slide-y-transition> *@
                </v-container>
                <page-loading></page-loading>
            </v-content>
            <v-snackbar :timeout   ="snackBar.timeout"
                        :top       ="snackBar.y === 'top'"
                        :bottom    ="snackBar.y === 'bottom'"
                        :right     ="snackBar.x === 'right'"
                        :left      ="snackBar.x === 'left'"
                        :multi-line="snackBar.mode === 'multi-line'"
                        :vertical  ="snackBar.mode === 'vertical'"
                        v-model    ="snackBar.show">
                {{snackBar.message}}
                <v-btn flat color="primary" v-on:click.native="snackBar.show = false">Close</v-btn>
            </v-snackbar>
            <v-dialog v-model="pageAlert.show" persistent max-width="450">
                <v-card>
                    <v-card-title class="headline">{{pageAlert.alertTitle}}</v-card-title>
                    <v-card-text v-html="pageAlert.alertMessage"></v-card-text>
                    <v-card-actions>
                        <v-spacer></v-spacer>
                        <v-btn color="green darken-1" flat v-on:click.native="pageAlert.show = false">Close</v-btn>
                    </v-card-actions>
                </v-card>
            </v-dialog>
        </v-app>
    </div>
    <script>
        window.BaseUrl = '@(Url.Content("~/"))';
    </script>
    <script src="~/dist/app.bundle.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>