Controllers/SecurityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AspNetCoreVueTypescriptStarter.Infrastructure.Extensions;
using AspNetCoreVueTypescriptStarter.Infrastructure.Filters;

namespace AspNetCoreVueTypescriptStarter.Controllers
{
    [LoggingFilter]
    public class SecurityController : BaseController
    {
        private readonly ILogger<SecurityController> _logger;

        public SecurityController(ILoggerFactory loggerFactory,
                                  ILogger<SecurityController> logger,
                                  ApplicationConfig applicationConfig,
                                  IHttpContextAccessor ctxAccessor) : base(loggerFactory, applicationConfig, ctxAccessor)
        {
            _logger = logger;
        }

        [HttpGet]
        [Route("SecurityNotice")]
        public IActionResult SecurityNotice()
        {
            _logger.LogInformation("Security Notice Shown ...");

            if (Request.IsAjaxRequest())
            {
                _logger.LogError("Security Notice AJAX ...");
            }

            return View("MustAcknowledge");
        }

        [HttpPost]
        [Route("SecurityNotice")]
        [ValidateAntiForgeryToken]
        public IActionResult SecurityNotice([FromForm]string response)
        {
            _logger.LogInformation("Security Notice Response ...");

            if (response.IsNullOrWhiteSpace() || response.ToLower() != "true")
            {
                _logger.LogError($"Security Notice Response detected an invalid reponse {response} from the page. Some monkey business has been detected.");
                ModelState.AddModelError("Error", "An invalid reponse was detected. Please dont monkey with me. This has been logged and IT alerted.");
            }
            if (ModelState.IsValid)
            {
                _logger.LogInformation("Updating agree cookie ...");
                UpdateIAgreeCookie();


                var url = TempData["returnUrl"].ToStringOrDefault();
                _logger.LogInformation($"returnUrl = {url}");

                if (url == @"/") { url = ""; }

                if (url.IsNotNullOrWhiteSpace()
                  && !url.ToLower().Contains("securitynotice")
                  && !url.ToLower().Contains("error")) //paranoid bout infinite redirects
                {
                    _logger.LogInformation($"Trying to redirect to {url}");
                    return LocalRedirect(url);
                }

                _logger.LogInformation("Redirecting to Default ...");
                return RedirectToAction("Index", "Root"); //todo extract to class
            }

            ViewBag.Error = "An Error Occurred. Perhaps you shouldnt mess with the page";

            return View("MustAcknowledge");
        }

    }
}

Views/Security/MustAcknowledge.cshtml
@{
    ViewData["Title"] = "Security Confirmation";
}
<component inline-template is="mustAcknowledgePage">
    <v-layout row wrap class="full-height">
        <v-card hover class="ma-2">
            <v-card-title>
                @if (ViewBag.Error != null)
                {
                    <h1 class="headline"><v-icon x-large color="red">warning</v-icon> @ViewBag.Error</h1>
                }
                else
                {
                    <h1 class="headline"><v-icon x-large color="red">warning</v-icon> Attention!</h1>
                }
            </v-card-title>
            <v-card-text class="flex-spacer">
                <p class="title">This application contains Sensitive information.</p>
                <p class="subheading"> Access to and use of this system is restricted to authorized individuals only.</p>
                <p class="body-2">
                    By clicking "I Agree", you are confirming you are authorized to use this system and you will abide by applicable federal and state laws, Executive Orders, directives, policies, regulations, standards, and accordance to the Information Security Policies.
                </p>
                <form asp-controller="Security" asp-action="SecurityNotice" method="post">
                    <input name="response" type="hidden" value="true" />
                    <v-btn color="warning" type="submit">I Agree</v-btn>
                </form>
            </v-card-text>
        </v-card>
    </v-layout>
</component>

@section Scripts {
}